apiVersion: apis.kcp.dev/v1alpha1
kind: APIBinding
metadata:
  name: data.my.domain
spec:
  reference:
    workspace:
      exportName: data.my.domain
  permissionClaims:
  - resource: "secrets"
    state: "Accepted"
  - resource: "configmaps"
    state: "Accepted"
  - resource: "namespaces"
    state: "Accepted"