---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: kcp-manager-role
rules:
  - apiGroups:
      - apis.kcp.io
    resources:
      - apiexports
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - apis.kcp.io
    resources:
      - apiexports/content
    verbs:
      - "*"
