nameReference:
  - kind: APIResourceSchema
    fieldSpecs:
      - kind: APIExport
        path: spec/latestResourceSchemas
  - kind: APIExport
    fieldSpecs:
      - kind: ClusterRole
        path: rules/resourceNames
