nameReference:
- kind: APIResourceSchema
  fieldSpecs:
  - kind: APIExport
    path: spec/latestResourceSchemas
- kind: APIExport
  fieldSpecs:
  - kind: APIBinding
    path: spec/reference/workspace/exportName

